import React from 'react';
import HospitalLogo from './HospitalLogo';
import '../../styles/print-report.css';

interface PrintReportProps {
  title: string;
  description: string;
  reportData: any[];
  columns: string[];
  startDate: string;
  endDate: string;
  timeRange: string;
  reportType: string;
}

const PrintReport: React.FC<PrintReportProps> = ({
  title,
  description,
  reportData,
  columns,
  startDate,
  endDate,
  timeRange,
  reportType
}) => {
  const formatMoney = (amount: number) => {
    return new Intl.NumberFormat('en-PK', {
      style: 'currency',
      currency: 'PKR',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  return (
    <div className="print-report-container">
      {/* Print Header with Logo */}
      <div className="print-header">
        <div className="print-header-content">
          <div className="print-logo">
            <HospitalLogo size="lg" className="print-logo-img" />
          </div>
          <div className="print-header-text">
            <h1 className="print-title">Shaukat International Hospital</h1>
            <p className="print-subtitle">Professional Healthcare Services</p>
            <p className="print-tagline">Quality Care, Trusted Results</p>
            <p className="print-address">Lahore, Pakistan</p>
          </div>
        </div>
      </div>

      {/* Report Title */}
      <h2 className="print-report-title">{title}</h2>
      <p className="print-report-description">{description}</p>

      {/* Report Information */}
      <div className="print-report-info">
        <div>
          <strong>Report Period:</strong> {startDate} to {endDate}
          {timeRange !== 'daily' && <span style={{ color: '#2563eb', marginLeft: '10px' }}>(Auto-set for {timeRange})</span>}
        </div>
        <div>
          <strong>Generated:</strong> {new Date().toLocaleDateString()}
        </div>
        <div>
          <strong>Report Type:</strong> {reportType}
        </div>
      </div>

      {/* Report Table */}
      <div className="print-table-container">
        <table className="print-table">
          <thead>
            <tr>
              {columns.map((column, index) => (
                <th key={index} className="print-table-header">{column}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {reportData.map((row, rowIndex) => (
              <tr key={rowIndex} className={rowIndex % 2 === 0 ? 'print-table-row-even' : 'print-table-row-odd'}>
                {Object.values(row).map((cell, cellIndex) => (
                  <td key={cellIndex} className="print-table-cell">
                    {typeof cell === 'number' ? formatMoney(cell) : String(cell)}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Report Summary */}
      <div className="print-summary">
        <div className="print-summary-item">
          <div className="print-summary-value">{reportData.length}</div>
          <div className="print-summary-label">Total Records</div>
        </div>
        <div className="print-summary-item">
          <div className="print-summary-value">{new Date().toLocaleDateString()}</div>
          <div className="print-summary-label">Report Date</div>
        </div>
        <div className="print-summary-item">
          <div className="print-summary-value">{timeRange.charAt(0).toUpperCase() + timeRange.slice(1)}</div>
          <div className="print-summary-label">Time Period</div>
        </div>
        <div className="print-summary-item">
          <div className="print-summary-value">{reportType}</div>
          <div className="print-summary-label">Report Type</div>
        </div>
      </div>

      {/* Print Footer */}
      <div className="print-footer">
        <div className="print-footer-content">
          <div className="print-footer-title">Official Document</div>
          <p style={{ margin: '5px 0' }}>This report was generated by Shaukat International Hospital Management System</p>
          <p style={{ margin: '5px 0' }}>For any queries, please contact the administration office</p>
        </div>
        <div className="print-footer-info">
          <span>Page 1 of 1</span>
          <span>Generated on: {new Date().toLocaleString()}</span>
        </div>
      </div>
    </div>
  );
};

export default PrintReport;
